version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  ai_service:
    build: ./ai_service
    container_name: proyectoia1-ai_service
    ports:
      - "5001:5001"
    environment:
      - OLLAMA_MODELS_PATH=/root/.ollama
    volumes:
      - ~/.ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5001"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: proyectoia1-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/commentsDB
      - AI_SERVICE_URL=http://ai_service:5001
    depends_on:
      mongodb:
        condition: service_healthy
      ai_service:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: proyectoia1-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
