services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - ai_service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  ai_service:
    build: ./ai_service
    ports:
      - "5001:5001"
    environment:
      - OLLAMA_MODELS_PATH=/root/.ollama
    volumes:
      - ~/.ollama:/root/.ollama
